import React, { useState, useEffect } from 'react';
import { useApp } from '../context/AppContext';
import {
  Database,
  CheckCircle2,
  XCircle,
  RefreshCw,
  Copy,
  Check,
  AlertTriangle,
  ExternalLink,
  Layers,
  ShieldAlert,
  DownloadCloud,
  UploadCloud,
  Key,
  Globe,
  Settings2,
  Save,
  RotateCcw,
} from 'lucide-react';
import {
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  DEFAULT_SUPABASE_URL,
  DEFAULT_SUPABASE_ANON_KEY,
  updateSupabaseClient,
  resetToDefaultSupabaseClient,
  getStoredSupabaseConfig,
} from '../lib/supabase';

interface Props {
  isOpen: boolean;
  onClose: () => void;
}

export const SupabaseStatusModal: React.FC<Props> = ({ isOpen, onClose }) => {
  const {
    supabaseStatus,
    isTestingSupabase,
    checkSupabaseHealth,
    syncDataToSupabase,
    isSyncingWithSupabase,
    loadDataFromSupabase,
    isLoadingFromSupabase,
  } = useApp();

  const [activeTab, setActiveTab] = useState<'status' | 'config' | 'sql'>('status');

  // Custom Supabase credentials
  const [customUrl, setCustomUrl] = useState('');
  const [customKey, setCustomKey] = useState('');
  const [savedConfigFeedback, setSavedConfigFeedback] = useState<string | null>(null);

  const [copiedSql, setCopiedSql] = useState(false);
  const [copiedDdlSql, setCopiedDdlSql] = useState(false);
  const [syncFeedback, setSyncFeedback] = useState<{
    success?: boolean;
    message?: string;
  } | null>(null);

  useEffect(() => {
    if (isOpen) {
      const cfg = getStoredSupabaseConfig();
      setCustomUrl(cfg.url);
      setCustomKey(cfg.anonKey);
      checkSupabaseHealth();
    }
  }, [isOpen]);

  const rlsFixSql = `-- 1. NONAKTIFKAN RLS SUPABASE AGAR APLIKASI BISA MENULIS DATA:
ALTER TABLE IF EXISTS roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS students DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS selection_candidates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS selection_votes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS pleno_evaluations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS candidates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS voting_attendances DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS final_votes DISABLE ROW LEVEL SECURITY;`;

  const fullDdlSql = `-- ====================================================================
-- SKEMA LENGKAP 10 TABEL DATABASE PILKETOS SMP AL-MUTTAQIN (POSTGRESQL)
-- ====================================================================

-- 1. ROLES
CREATE TABLE IF NOT EXISTS roles (
    id INT PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

-- 2. USERS (ADMIN & GURU & PETUGAS)
CREATE TABLE IF NOT EXISTS users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role_id INT REFERENCES roles(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. KELAS & ROMBEL
CREATE TABLE IF NOT EXISTS classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade INT NOT NULL CHECK (grade IN (7, 8, 9)),
    rombel VARCHAR(10) NOT NULL,
    UNIQUE(grade, rombel)
);

-- 4. SISWA
CREATE TABLE IF NOT EXISTS students (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. KANDIDAT BAKAL CALON RESMI (ADMIN SELECTION POOL)
CREATE TABLE IF NOT EXISTS selection_candidates (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    student_id UUID REFERENCES students(id) ON DELETE CASCADE UNIQUE,
    notes TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. SUARA SELEKSI (TAHAP 1)
CREATE TABLE IF NOT EXISTS selection_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voter_student_id UUID REFERENCES students(id) ON DELETE CASCADE,
    nominated_student_id UUID REFERENCES students(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(voter_student_id, nominated_student_id)
);

-- 7. CATATAN PLENO DEWAN GURU (TAHAP 2)
CREATE TABLE IF NOT EXISTS pleno_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES students(id) ON DELETE CASCADE UNIQUE,
    teacher_user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    teacher_notes TEXT,
    is_selected_for_paslon BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. PASANGAN CALON TETAP (PASLON 1, 2, 3)
CREATE TABLE IF NOT EXISTS candidates (
    id INT PRIMARY KEY,
    chairman_student_id UUID REFERENCES students(id) ON DELETE CASCADE,
    vice_chairman_student_id UUID REFERENCES students(id) ON DELETE CASCADE,
    vision_mission TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. ABSENSI E-VOTING (TAHAP 3)
CREATE TABLE IF NOT EXISTS voting_attendances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES students(id) ON DELETE CASCADE UNIQUE,
    attended_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. SUARA PEMILIHAN UTAMA / COBLOSAN (ANONIM)
CREATE TABLE IF NOT EXISTS final_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id INT REFERENCES candidates(id) ON DELETE CASCADE,
    voted_at TIMESTAMPTZ DEFAULT NOW()
);

-- NONAKTIFKAN RLS AGAR CLIENT DAPAT TERHUBUNG LANGSUNG
ALTER TABLE IF EXISTS roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS students DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS selection_candidates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS selection_votes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS pleno_evaluations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS candidates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS voting_attendances DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS final_votes DISABLE ROW LEVEL SECURITY;`;

  const handleCopySql = (sql: string, type: 'rls' | 'ddl') => {
    navigator.clipboard.writeText(sql);
    if (type === 'rls') {
      setCopiedSql(true);
      setTimeout(() => setCopiedSql(false), 2500);
    } else {
      setCopiedDdlSql(true);
      setTimeout(() => setCopiedDdlSql(false), 2500);
    }
  };

  const handleSaveCredentials = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!customUrl.trim() || !customKey.trim()) {
      setSavedConfigFeedback('URL dan Anon Key tidak boleh kosong.');
      return;
    }

    updateSupabaseClient(customUrl, customKey);
    setSavedConfigFeedback('Kredensial database berhasil disimpan! Sedang menguji koneksi...');
    const res = await checkSupabaseHealth();
    if (res && res.isConnected) {
      setSavedConfigFeedback('Terhubung dengan sukses ke Supabase!');
      setActiveTab('status');
    } else {
      setSavedConfigFeedback('Kredensial disimpan, namun belum terhubung. Periksa URL dan API Key.');
    }
    setTimeout(() => setSavedConfigFeedback(null), 5000);
  };

  const handleResetToDefault = async () => {
    resetToDefaultSupabaseClient();
    setCustomUrl(DEFAULT_SUPABASE_URL);
    setCustomKey(DEFAULT_SUPABASE_ANON_KEY);
    setSavedConfigFeedback('Kredensial dikembalikan ke database bawaan.');
    await checkSupabaseHealth();
    setTimeout(() => setSavedConfigFeedback(null), 4000);
  };

  const handleSyncNow = async () => {
    setSyncFeedback(null);
    const res = await syncDataToSupabase();
    setSyncFeedback(res);
  };

  const handlePullFromSupabase = async () => {
    setSyncFeedback(null);
    const res = await loadDataFromSupabase();
    setSyncFeedback(res);
    await checkSupabaseHealth();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-150">
      <div className="bg-white rounded-2xl border border-slate-200 shadow-2xl max-w-3xl w-full max-h-[90vh] flex flex-col overflow-hidden">
        {/* Modal Header */}
        <div className="p-5 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-600">
              <Database className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-sm font-bold text-slate-900">
                  Integrasi & Sinkronisasi Database Supabase PostgreSQL
                </h3>
                {supabaseStatus?.isConnected ? (
                  <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-800 border border-emerald-300">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                    Terhubung
                  </span>
                ) : (
                  <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-rose-100 text-rose-800 border border-rose-300">
                    <span className="w-1.5 h-1.5 rounded-full bg-rose-500" />
                    Belum Terhubung
                  </span>
                )}
              </div>
              <p className="text-xs text-slate-500 mt-0.5 font-mono truncate max-w-lg">
                {SUPABASE_URL}
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-600 p-1.5 rounded-lg hover:bg-slate-100 transition-colors text-xs font-semibold"
          >
            ✕ Tutup
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="px-6 border-b border-slate-200 bg-slate-50/30 flex items-center gap-4 text-xs font-semibold">
          <button
            onClick={() => setActiveTab('status')}
            className={`py-3 border-b-2 transition-colors flex items-center gap-1.5 ${
              activeTab === 'status'
                ? 'border-emerald-600 text-emerald-700'
                : 'border-transparent text-slate-500 hover:text-slate-800'
            }`}
          >
            <Database className="w-3.5 h-3.5" />
            <span>Status 10 Tabel Database</span>
          </button>

          <button
            onClick={() => setActiveTab('config')}
            className={`py-3 border-b-2 transition-colors flex items-center gap-1.5 ${
              activeTab === 'config'
                ? 'border-emerald-600 text-emerald-700'
                : 'border-transparent text-slate-500 hover:text-slate-800'
            }`}
          >
            <Settings2 className="w-3.5 h-3.5" />
            <span>Pengaturan URL & API Key</span>
          </button>

          <button
            onClick={() => setActiveTab('sql')}
            className={`py-3 border-b-2 transition-colors flex items-center gap-1.5 ${
              activeTab === 'sql'
                ? 'border-emerald-600 text-emerald-700'
                : 'border-transparent text-slate-500 hover:text-slate-800'
            }`}
          >
            <ShieldAlert className="w-3.5 h-3.5" />
            <span>Skema SQL & Izin RLS</span>
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-6 text-xs flex-1">
          {/* TAB 1: STATUS & DATA SYNC */}
          {activeTab === 'status' && (
            <div className="space-y-6">
              {/* Connection Actions Card */}
              <div className="p-4 rounded-xl border border-slate-200 bg-slate-50 space-y-3">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                  <div>
                    <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider block">
                      Target Database Aktif
                    </span>
                    <span className="font-semibold text-slate-900 text-xs font-mono break-all">
                      {SUPABASE_URL}
                    </span>
                  </div>

                  <div className="flex flex-wrap items-center gap-2 shrink-0">
                    <button
                      onClick={checkSupabaseHealth}
                      disabled={isTestingSupabase}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 rounded-lg font-medium transition-colors disabled:opacity-50"
                      title="Periksa koneksi dan hitung baris data pada seluruh tabel"
                    >
                      <RefreshCw className={`w-3.5 h-3.5 ${isTestingSupabase ? 'animate-spin' : ''}`} />
                      <span>Uji Koneksi</span>
                    </button>

                    <button
                      onClick={handlePullFromSupabase}
                      disabled={isLoadingFromSupabase}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-sky-50 hover:bg-sky-100 text-sky-700 border border-sky-200 rounded-lg font-bold transition-colors disabled:opacity-50"
                      title="Ambil data dari tabel Supabase dan tampilkan di aplikasi"
                    >
                      <DownloadCloud className={`w-3.5 h-3.5 ${isLoadingFromSupabase ? 'animate-bounce' : ''}`} />
                      <span>{isLoadingFromSupabase ? 'Menarik...' : 'Tarik Data dari Database'}</span>
                    </button>

                    <button
                      onClick={handleSyncNow}
                      disabled={isSyncingWithSupabase}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg font-bold transition-colors disabled:opacity-50 shadow-xs"
                      title="Kirim dan simpan data master aplikasi ke tabel database Supabase"
                    >
                      <UploadCloud className={`w-3.5 h-3.5 ${isSyncingWithSupabase ? 'animate-spin' : ''}`} />
                      <span>{isSyncingWithSupabase ? 'Mengirim...' : 'Kirim Master Data'}</span>
                    </button>
                  </div>
                </div>

                {syncFeedback && (
                  <div
                    className={`p-3 rounded-lg border flex items-start gap-2.5 ${
                      syncFeedback.success
                        ? 'bg-emerald-50 border-emerald-200 text-emerald-800'
                        : 'bg-rose-50 border-rose-200 text-rose-800'
                    }`}
                  >
                    {syncFeedback.success ? (
                      <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                    ) : (
                      <AlertTriangle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
                    )}
                    <div className="space-y-1">
                      <p className="font-semibold text-xs">{syncFeedback.message}</p>
                    </div>
                  </div>
                )}
              </div>

              {/* Table Diagnostics Grid */}
              <div>
                <div className="flex items-center justify-between mb-2.5">
                  <h4 className="font-bold text-slate-800 flex items-center gap-1.5 text-xs">
                    <Layers className="w-4 h-4 text-emerald-600" />
                    <span>Daftar 10 Tabel Database Terdeteksi:</span>
                  </h4>
                  <span className="text-[11px] text-slate-400 font-mono">
                    Diperbarui: {supabaseStatus?.checkedAt || 'Baru saja'}
                  </span>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-2.5">
                  {supabaseStatus?.tables &&
                    Object.entries(supabaseStatus.tables).map(([tableName, info]) => (
                      <div
                        key={tableName}
                        className={`p-3 rounded-xl border flex items-center justify-between ${
                          info.exists
                            ? 'bg-emerald-50/40 border-emerald-200'
                            : 'bg-slate-50 border-slate-200'
                        }`}
                      >
                        <div className="min-w-0">
                          <span className="font-mono font-bold text-slate-800 block truncate text-xs">
                            {tableName}
                          </span>
                          <span className="text-[11px] text-slate-500 font-medium">
                            {info.exists ? `${info.count} baris data` : 'Belum dibuat / RLS lock'}
                          </span>
                        </div>

                        {info.exists ? (
                          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 ml-2" />
                        ) : (
                          <XCircle className="w-4 h-4 text-rose-500 shrink-0 ml-2" />
                        )}
                      </div>
                    ))}
                </div>
              </div>

              {/* Quick RLS Warning if any */}
              {supabaseStatus?.hasRlsIssue && (
                <div className="p-4 rounded-xl border border-amber-300 bg-amber-50 flex items-start gap-3">
                  <ShieldAlert className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
                  <div className="space-y-1">
                    <h5 className="font-bold text-amber-900 text-xs">
                      Peringatan: Row Level Security (RLS) Mengunci Tabel
                    </h5>
                    <p className="text-amber-800 text-[11px] leading-relaxed">
                      Tabel database sudah dibuat, tetapi Supabase mengunci akses query. Silakan buka tab <strong>"Skema SQL & Izin RLS"</strong> untuk menyalin kode penonaktifan RLS dan jalankan di SQL Editor Supabase.
                    </p>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* TAB 2: CONFIGURATION (CUSTOM URL & KEY) */}
          {activeTab === 'config' && (
            <form onSubmit={handleSaveCredentials} className="space-y-4">
              <div className="p-4 rounded-xl bg-blue-50 border border-blue-200 text-blue-900 leading-relaxed text-[11px]">
                <p className="font-bold">Hubungkan ke Project Supabase Anda:</p>
                <p className="mt-0.5">
                  Jika Anda telah membuat project sendiri di <strong>supabase.com</strong>, masukkan <em>Project URL</em> dan <em>Project API Key (anon/public)</em> dari menu <strong>Project Settings &gt; API</strong> di bawah ini.
                </p>
              </div>

              {savedConfigFeedback && (
                <div className="p-3 rounded-lg bg-emerald-50 border border-emerald-200 text-emerald-800 font-medium">
                  {savedConfigFeedback}
                </div>
              )}

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1 flex items-center gap-1.5">
                  <Globe className="w-3.5 h-3.5 text-slate-500" />
                  <span>Supabase Project URL</span>
                </label>
                <input
                  type="url"
                  value={customUrl}
                  onChange={(e) => setCustomUrl(e.target.value)}
                  placeholder="https://your-project.supabase.co"
                  required
                  className="w-full text-xs font-mono bg-white text-slate-900 border border-slate-300 rounded-lg p-2.5 focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1 flex items-center gap-1.5">
                  <Key className="w-3.5 h-3.5 text-slate-500" />
                  <span>Supabase Anon / Public API Key</span>
                </label>
                <textarea
                  value={customKey}
                  onChange={(e) => setCustomKey(e.target.value)}
                  placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  rows={3}
                  required
                  className="w-full text-xs font-mono bg-white text-slate-900 border border-slate-300 rounded-lg p-2.5 focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              <div className="flex items-center justify-between pt-2">
                <button
                  type="button"
                  onClick={handleResetToDefault}
                  className="flex items-center gap-1.5 px-3 py-2 text-xs font-medium text-slate-600 hover:bg-slate-100 rounded-lg transition-colors"
                >
                  <RotateCcw className="w-3.5 h-3.5" />
                  <span>Kembalikan Default</span>
                </button>

                <button
                  type="submit"
                  className="flex items-center gap-2 px-5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg text-xs font-bold transition-colors shadow-xs"
                >
                  <Save className="w-4 h-4" />
                  <span>Simpan & Hubungkan Database</span>
                </button>
              </div>
            </form>
          )}

          {/* TAB 3: SQL & RLS CODE */}
          {activeTab === 'sql' && (
            <div className="space-y-5">
              {/* RLS Fix Box */}
              <div className="p-4 rounded-xl border border-amber-200 bg-amber-50/70 space-y-3">
                <div className="flex items-start justify-between">
                  <div className="flex items-start gap-2.5">
                    <ShieldAlert className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
                    <div>
                      <h5 className="font-bold text-amber-900 text-xs">
                        1. Script Membuka Izin Akses (Disable RLS):
                      </h5>
                      <p className="text-amber-800 text-[11px] leading-relaxed mt-0.5">
                        Jalankan kode ini di <strong>Supabase Dashboard &gt; SQL Editor</strong> jika browser menampilkan error izin RLS.
                      </p>
                    </div>
                  </div>

                  <button
                    onClick={() => handleCopySql(rlsFixSql, 'rls')}
                    className="flex items-center gap-1 px-3 py-1.5 bg-slate-900 hover:bg-slate-800 text-white rounded-lg text-xs font-medium transition-colors shrink-0"
                  >
                    {copiedSql ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-400" />
                        <span className="text-emerald-400 font-bold">Tersalin</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Salin RLS SQL</span>
                      </>
                    )}
                  </button>
                </div>

                <pre className="bg-slate-900 text-emerald-400 p-3 rounded-lg text-[11px] font-mono overflow-x-auto selection:bg-emerald-800 selection:text-white">
                  {rlsFixSql}
                </pre>
              </div>

              {/* Full DDL Box */}
              <div className="p-4 rounded-xl border border-slate-200 bg-slate-50 space-y-3">
                <div className="flex items-start justify-between">
                  <div>
                    <h5 className="font-bold text-slate-900 text-xs">
                      2. Skema Lengkap 10 Tabel Database (DDL):
                    </h5>
                    <p className="text-slate-600 text-[11px] mt-0.5">
                      Gunakan skema ini untuk membuat seluruh tabel sekaligus secara otomatis di database PostgreSQL Supabase.
                    </p>
                  </div>

                  <button
                    onClick={() => handleCopySql(fullDdlSql, 'ddl')}
                    className="flex items-center gap-1 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg text-xs font-bold transition-colors shrink-0 shadow-xs"
                  >
                    {copiedDdlSql ? (
                      <>
                        <Check className="w-3.5 h-3.5" />
                        <span>Tersalin</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Salin Seluruh SQL DDL</span>
                      </>
                    )}
                  </button>
                </div>

                <pre className="bg-slate-900 text-slate-300 p-3.5 rounded-lg text-[10px] font-mono overflow-x-auto max-h-56 leading-relaxed">
                  {fullDdlSql}
                </pre>
              </div>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-slate-100 bg-slate-50 flex items-center justify-between text-xs">
          <a
            href="https://supabase.com/dashboard"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1.5 text-emerald-700 hover:text-emerald-800 font-semibold"
          >
            <span>Buka Supabase Dashboard</span>
            <ExternalLink className="w-3.5 h-3.5" />
          </a>

          <button
            onClick={onClose}
            className="px-5 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-lg font-bold transition-colors"
          >
            Tutup
          </button>
        </div>
      </div>
    </div>
  );
};
