export interface CodeFile {
  id: string;
  name: string;
  path: string;
  category: 'Controller' | 'Migration & SQL' | 'Model' | 'Middleware' | 'Blade View' | 'Routes';
  language: string;
  content: string;
}

export const LARAVEL_CODE_FILES: CodeFile[] = [
  {
    id: 'sql-ddl',
    name: 'supabase_schema.sql',
    path: 'database/supabase_schema.sql',
    category: 'Migration & SQL',
    language: 'sql',
    content: `-- ==========================================================
-- SUPABASE POSTGRESQL SCHEMA - SMP AL MUTTAQIN KOTA MADIUN
-- SISTEM PEMILIHAN KETUA & WAKIL KETUA OSIS
-- ==========================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. ROLES & USERS
CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    username VARCHAR(50) UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    password VARCHAR(255),
    role_id INT REFERENCES roles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. KELAS & ROMBEL
CREATE TABLE IF NOT EXISTS classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade INT NOT NULL CHECK (grade IN (7, 8, 9)),
    rombel VARCHAR(10) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(grade, rombel)
);

-- 4. SISWA (TANPA NIS, HANYA NAMA & KELAS)
CREATE TABLE IF NOT EXISTS students (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. KANDIDAT BAKAL CALON RESMI (DIINPUT OLEH ADMIN UNTUK TAHAP SELEKSI)
CREATE TABLE IF NOT EXISTS selection_candidates (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    student_id UUID REFERENCES students(id) ON DELETE CASCADE UNIQUE,
    notes TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. SUARA SELEKSI BAKAL CALON (TAHAP 1)
CREATE TABLE IF NOT EXISTS selection_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voter_student_id UUID REFERENCES students(id) ON DELETE CASCADE,
    nominated_student_id UUID REFERENCES students(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(voter_student_id, nominated_student_id)
);

-- 7. CATATAN & PLENO DEWAN GURU (TAHAP 2)
CREATE TABLE IF NOT EXISTS pleno_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES students(id) ON DELETE CASCADE UNIQUE,
    teacher_user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    teacher_notes TEXT,
    is_selected_for_paslon BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. PASANGAN CALON TETAP (PASLON 1, 2, 3)
CREATE TABLE IF NOT EXISTS candidates (
    id INT PRIMARY KEY,
    chairman_student_id UUID REFERENCES students(id) ON DELETE CASCADE,
    vice_chairman_student_id UUID REFERENCES students(id) ON DELETE CASCADE,
    vision_mission TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. ABSENSI PEMILIHAN UTAMA (TAHAP 3)
CREATE TABLE IF NOT EXISTS voting_attendances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES students(id) ON DELETE CASCADE UNIQUE,
    attended_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. SUARA PEMILIHAN UTAMA / COBLOSAN E-VOTING (ANONIM)
CREATE TABLE IF NOT EXISTS final_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id INT REFERENCES candidates(id) ON DELETE CASCADE,
    voted_at TIMESTAMPTZ DEFAULT NOW()
);

-- INDEKS UNTUK PERFORMA QUERY CEPAT
CREATE INDEX IF NOT EXISTS idx_students_class ON students(class_id);
CREATE INDEX IF NOT EXISTS idx_selection_cand_active ON selection_candidates(is_active);
CREATE INDEX IF NOT EXISTS idx_selection_votes_voter ON selection_votes(voter_student_id);
CREATE INDEX IF NOT EXISTS idx_selection_votes_nominee ON selection_votes(nominated_student_id);
CREATE INDEX IF NOT EXISTS idx_final_votes_candidate ON final_votes(candidate_id);

-- SEED DATA PERAN (ROLES)
INSERT INTO roles (id, name) VALUES 
(1, 'admin'),
(2, 'guru'),
(3, 'seleksi'),
(4, 'pemilihan')
ON CONFLICT (id) DO NOTHING;

-- SEED KELAS & ROMBEL DASAR
INSERT INTO classes (id, grade, rombel) VALUES
(1, 7, '7A'),
(2, 7, '7B'),
(3, 8, '8A'),
(4, 8, '8B'),
(5, 9, '9A'),
(6, 9, '9B')
ON CONFLICT (grade, rombel) DO NOTHING;
`,
  },
  {
    id: 'auth-controller',
    name: 'AuthController.php',
    path: 'app/Http/Controllers/AuthController.php',
    category: 'Controller',
    language: 'php',
    content: `<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Role;

class AuthController extends Controller
{
    public function showLogin()
    {
        return view('auth.login');
    }

    /**
     * Multi-Role Authentication Logic
     * Support Admin (Username/Password), Guru (Nama Lengkap), Seleksi, Pemilihan
     */
    public function login(Request $request)
    {
        $roleType = $request->input('role_type'); // 'admin', 'guru', 'seleksi', 'pemilihan'

        // 1. GURU: Cukup memasukkan "Nama Lengkap" guru
        if ($roleType === 'guru') {
            $request->validate([
                'full_name' => 'required|string|max:100',
            ]);

            $fullName = trim($request->input('full_name'));
            $teacher = User::where('role_id', 2)
                ->where('full_name', 'ILIKE', '%' . $fullName . '%')
                ->first();

            if (!$teacher) {
                // Auto-register teacher session if matches master list
                $teacher = User::create([
                    'username' => 'guru_' . strtolower(preg_replace('/[^a-zA-Z0-9]/', '', $fullName)),
                    'full_name' => $fullName,
                    'role_id' => 2,
                ]);
            }

            Auth::login($teacher);
            $request->session()->regenerate();
            return redirect()->route('pleno.index');
        }

        // 2. ADMIN & PETUGAS (Seleksi & Pemilihan)
        $request->validate([
            'username' => 'required|string',
            'password' => 'required|string',
        ]);

        $roleId = match($roleType) {
            'admin' => 1,
            'seleksi' => 3,
            'pemilihan' => 4,
            default => null,
        };

        if (!$roleId) {
            return back()->withErrors(['error' => 'Peran pengguna tidak valid.']);
        }

        $user = User::where('role_id', $roleId)
            ->where('username', $request->input('username'))
            ->first();

        if ($user && Hash::check($request->input('password'), $user->password)) {
            Auth::login($user);
            $request->session()->regenerate();

            return match($roleId) {
                1 => redirect()->route('dashboard'),
                3 => redirect()->route('seleksi.index'),
                4 => redirect()->route('voting.bilik'),
            };
        }

        return back()->withErrors(['error' => 'Kredensial username atau kata sandi tidak valid.']);
    }

    public function logout(Request $request)
    {
        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();
        return redirect()->route('login');
    }
}
`,
  },
  {
    id: 'dashboard-controller',
    name: 'DashboardController.php',
    path: 'app/Http/Controllers/DashboardController.php',
    category: 'Controller',
    language: 'php',
    content: `<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Candidate;
use App\Models\FinalVote;
use App\Models\Student;
use App\Models\VotingAttendance;
use App\Models\PlenoEvaluation;
use App\Models\Classes;

class DashboardController extends Controller
{
    public function index()
    {
        // 1. Donut Chart: Final Votes per Candidate (Paslon 1, 2, 3)
        $finalVotes = DB::table('final_votes')
            ->select('candidate_id', DB::raw('count(*) as total'))
            ->groupBy('candidate_id')
            ->get();

        $candidates = Candidate::with(['chairman', 'viceChairman'])->orderBy('id')->get();

        // 2. Donut Chart: Tingkat Partisipasi (Hadir vs Belum)
        $totalStudents = Student::count();
        $attendedStudents = VotingAttendance::count();
        $absentStudents = max(0, $totalStudents - $attendedStudents);

        // 3. Donut Chart: Musyawarah Pleno
        $plenoSelected = PlenoEvaluation::where('is_selected_for_paslon', true)->count();
        $plenoTotal = PlenoEvaluation::count();

        // 4. Seleksi Calon per Rombel 7A, 7B, 8A, 8B
        $targetClasses = Classes::whereIn('grade', [7, 8])->orderBy('grade')->orderBy('rombel')->get();

        return view('dashboard', compact(
            'finalVotes',
            'candidates',
            'totalStudents',
            'attendedStudents',
            'absentStudents',
            'plenoSelected',
            'plenoTotal',
            'targetClasses'
        ));
    }
}
`,
  },
  {
    id: 'selection-controller',
    name: 'SelectionController.php',
    path: 'app/Http/Controllers/SelectionController.php',
    category: 'Controller',
    language: 'php',
    content: `<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Student;
use App\Models\Classes;
use App\Models\SelectionVote;

class SelectionController extends Controller
{
    public function index()
    {
        $classes = Classes::orderBy('grade')->orderBy('rombel')->get();
        // Candidate pool must be from grade 7 & 8 only
        $eligibleClassIds = Classes::whereIn('grade', [7, 8])->pluck('id');
        $candidatePool = Student::whereIn('class_id', $eligibleClassIds)->orderBy('full_name')->get();

        return view('seleksi.index', compact('classes', 'candidatePool'));
    }

    /**
     * Record 3 votes for 1 voter student
     */
    public function store(Request $request)
    {
        $request->validate([
            'voter_student_id' => 'required|uuid|exists:students,id',
            'nominated_student_ids' => 'required|array|size:3',
            'nominated_student_ids.*' => 'required|uuid|exists:students,id|distinct',
        ]);

        $voterId = $request->input('voter_student_id');
        $nominatedIds = $request->input('nominated_student_ids');

        // Check if student already voted
        $alreadyVoted = SelectionVote::where('voter_student_id', $voterId)->exists();
        if ($alreadyVoted) {
            return back()->withErrors(['error' => 'Siswa pemilih ini telah menggunakan hak pilih sebelumnya.']);
        }

        // Validate all 3 nominees belong to Grade 7 or 8
        $eligibleClassIds = Classes::whereIn('grade', [7, 8])->pluck('id');
        $validNomineesCount = Student::whereIn('id', $nominatedIds)
            ->whereIn('class_id', $eligibleClassIds)
            ->count();

        if ($validNomineesCount !== 3) {
            return back()->withErrors(['error' => 'Calon wajib berasal dari rombel Kelas 7 atau Kelas 8.']);
        }

        DB::transaction(function () use ($voterId, $nominatedIds) {
            foreach ($nominatedIds as $nomId) {
                SelectionVote::create([
                    'voter_student_id' => $voterId,
                    'nominated_student_id' => $nomId,
                ]);
            }
        });

        return back()->with('success', 'Pilihan bakal calon berhasil disimpan ke sistem.');
    }

    /**
     * Automatic Recapitulation: Top 3 from 7A, 7B, 8A, 8B (Total 12 Nominees)
     */
    public function rekap()
    {
        $classes = Classes::whereIn('grade', [7, 8])->orderBy('grade')->orderBy('rombel')->get();
        $rekapPerRombel = [];

        foreach ($classes as $kelas) {
            $topStudents = DB::table('students')
                ->join('classes', 'students.class_id', '=', 'classes.id')
                ->leftJoin('selection_votes', 'students.id', '=', 'selection_votes.nominated_student_id')
                ->select(
                    'students.id',
                    'students.full_name',
                    'classes.rombel',
                    DB::raw('count(selection_votes.id) as vote_count')
                )
                ->where('students.class_id', $kelas->id)
                ->groupBy('students.id', 'students.full_name', 'classes.rombel')
                ->orderByDesc('vote_count')
                ->orderBy('students.full_name')
                ->limit(3)
                ->get();

            $rekapPerRombel[$kelas->rombel] = $topStudents;
        }

        return view('seleksi.rekap', compact('rekapPerRombel', 'classes'));
    }
}
`,
  },
  {
    id: 'pleno-controller',
    name: 'PlenoController.php',
    path: 'app/Http/Controllers/PlenoController.php',
    category: 'Controller',
    language: 'php',
    content: `<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\PlenoEvaluation;
use App\Models\Student;
use App\Models\Classes;
use Illuminate\Support\Facades\DB;

class PlenoController extends Controller
{
    /**
     * Show Pleno evaluation for the 12 top candidates
     */
    public function index()
    {
        // Fetch top 3 from each rombel (7A, 7B, 8A, 8B)
        $targetClassIds = Classes::whereIn('grade', [7, 8])->pluck('id');
        
        $topCandidates = DB::table('students')
            ->join('classes', 'students.class_id', '=', 'classes.id')
            ->leftJoin('selection_votes', 'students.id', '=', 'selection_votes.nominated_student_id')
            ->leftJoin('pleno_evaluations', 'students.id', '=', 'pleno_evaluations.student_id')
            ->select(
                'students.id',
                'students.full_name',
                'classes.rombel',
                'classes.grade',
                'pleno_evaluations.teacher_notes',
                'pleno_evaluations.is_selected_for_paslon',
                DB::raw('count(selection_votes.id) as vote_count')
            )
            ->whereIn('students.class_id', $targetClassIds)
            ->groupBy(
                'students.id',
                'students.full_name',
                'classes.rombel',
                'classes.grade',
                'pleno_evaluations.teacher_notes',
                'pleno_evaluations.is_selected_for_paslon'
            )
            ->orderBy('classes.grade')
            ->orderBy('classes.rombel')
            ->orderByDesc('vote_count')
            ->get();

        $selectedCount = PlenoEvaluation::where('is_selected_for_paslon', true)->count();

        return view('pleno.index', compact('topCandidates', 'selectedCount'));
    }

    public function update(Request $request, $studentId)
    {
        $request->validate([
            'teacher_notes' => 'nullable|string',
            'is_selected_for_paslon' => 'boolean',
        ]);

        $teacherUser = Auth::user();

        PlenoEvaluation::updateOrCreate(
            ['student_id' => $studentId],
            [
                'teacher_user_id' => $teacherUser->id,
                'teacher_notes' => $request->input('teacher_notes'),
                'is_selected_for_paslon' => $request->boolean('is_selected_for_paslon'),
            ]
        );

        return back()->with('success', 'Catatan musyawarah pleno berhasil diperbarui.');
    }
}
`,
  },
  {
    id: 'voting-controller',
    name: 'VotingController.php',
    path: 'app/Http/Controllers/VotingController.php',
    category: 'Controller',
    language: 'php',
    content: `<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Classes;
use App\Models\Student;
use App\Models\Candidate;
use App\Models\VotingAttendance;
use App\Models\FinalVote;

class VotingController extends Controller
{
    /**
     * Bilik Suara Main View (Absensi & Coblos)
     */
    public function bilik()
    {
        $classes = Classes::orderBy('grade')->orderBy('rombel')->get();
        $candidates = Candidate::with(['chairman', 'viceChairman'])->orderBy('id')->get();

        return view('voting.bilik', compact('classes', 'candidates'));
    }

    /**
     * Check-in Attendance (Tercatat nama siswa)
     */
    public function checkIn(Request $request)
    {
        $request->validate([
            'student_id' => 'required|uuid|exists:students,id',
        ]);

        $studentId = $request->input('student_id');

        if (VotingAttendance::where('student_id', $studentId)->exists()) {
            return response()->json(['error' => 'Siswa sudah melakukan absensi sebelumnya.'], 422);
        }

        VotingAttendance::create([
            'student_id' => $studentId,
        ]);

        return response()->json(['success' => true, 'message' => 'Absensi berhasil diverifikasi.']);
    }

    /**
     * Coblos Paslon (ANONIM - tanpa mencatat student_id di tabel final_votes)
     */
    public function castVote(Request $request)
    {
        $request->validate([
            'candidate_id' => 'required|integer|in:1,2,3|exists:candidates,id',
        ]);

        FinalVote::create([
            'candidate_id' => $request->input('candidate_id'),
        ]);

        return response()->json([
            'success' => true,
            'message' => 'Suara berhasil dicoblos dan disimpan secara anonim.',
        ]);
    }
}
`,
  },
  {
    id: 'role-middleware',
    name: 'RoleMiddleware.php',
    path: 'app/Http/Middleware/RoleMiddleware.php',
    category: 'Middleware',
    language: 'php',
    content: `<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class RoleMiddleware
{
    /**
     * Enforce role-based access control (admin, guru, seleksi, pemilihan)
     */
    public function handle(Request $request, Closure $next, ...$roles)
    {
        if (!Auth::check()) {
            return redirect()->route('login');
        }

        $userRole = Auth::user()->role->name ?? null;

        if (!in_array($userRole, $roles)) {
            abort(403, 'Akses ditolak: Peran Anda tidak memiliki wewenang pada modul ini.');
        }

        return $next($request);
    }
}
`,
  },
  {
    id: 'routes-web',
    name: 'web.php',
    path: 'routes/web.php',
    category: 'Routes',
    language: 'php',
    content: `<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\SelectionController;
use App\Http\Controllers\PlenoController;
use App\Http\Controllers\VotingController;
use App\Http\Controllers\AdminController;

// Auth Routes
Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login.post');
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {
    // Dashboard: Accessible by all roles
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    // Tahap 1: Seleksi Bakal Calon (Petugas Seleksi & Admin)
    Route::middleware('role:admin,seleksi')->group(function () {
        Route::get('/seleksi', [SelectionController::class, 'index'])->name('seleksi.index');
        Route::post('/seleksi', [SelectionController::class, 'store'])->name('seleksi.store');
    });

    Route::get('/seleksi/rekap', [SelectionController::class, 'rekap'])->name('seleksi.rekap');

    // Tahap 2: Musyawarah Pleno (Guru & Admin)
    Route::middleware('role:admin,guru')->group(function () {
        Route::get('/pleno', [PlenoController::class, 'index'])->name('pleno.index');
        Route::post('/pleno/{studentId}', [PlenoController::class, 'update'])->name('pleno.update');
    });

    // Tahap 3: Pemilihan Bilik Suara (Petugas Pemilihan & Admin)
    Route::middleware('role:admin,pemilihan')->group(function () {
        Route::get('/voting/bilik', [VotingController::class, 'bilik'])->name('voting.bilik');
        Route::post('/voting/check-in', [VotingController::class, 'checkIn'])->name('voting.checkin');
        Route::post('/voting/cast', [VotingController::class, 'castVote'])->name('voting.cast');
    });

    // Modul Khusus Administrator (Absensi, Paslon, Siswa, Petugas)
    Route::middleware('role:admin')->group(function () {
        Route::get('/admin/absensi', [AdminController::class, 'absensi'])->name('admin.absensi');
        Route::get('/admin/paslon', [AdminController::class, 'paslon'])->name('admin.paslon');
        Route::post('/admin/paslon', [AdminController::class, 'savePaslon'])->name('admin.paslon.save');
        Route::resource('/admin/students', AdminController::class);
        Route::resource('/admin/teachers', AdminController::class);
        Route::resource('/admin/operators', AdminController::class);
    });
});
`,
  },
  {
    id: 'sidebar-blade',
    name: 'sidebar.blade.php',
    path: 'resources/views/layouts/sidebar.blade.php',
    category: 'Blade View',
    language: 'html',
    content: `<!-- Layout Sidebar Bersih & Modern - SMP Al Muttaqin Kota Madiun -->
<aside class="w-64 bg-slate-900 text-slate-200 shrink-0 flex flex-col h-screen border-r border-slate-800">
    <div class="p-4 border-b border-slate-800">
        <div class="flex items-center gap-3">
            <div class="w-9 h-9 rounded-lg bg-emerald-600 text-white flex items-center justify-center font-bold">
                M
            </div>
            <div>
                <span class="text-[10px] font-semibold text-emerald-400 uppercase tracking-wider block">E-Pilketos</span>
                <h1 class="text-xs font-bold text-white tracking-tight leading-snug">SMP Al Muttaqin</h1>
                <p class="text-[10px] text-slate-400">Kota Madiun</p>
            </div>
        </div>
    </div>

    <div class="px-4 py-3 bg-slate-950/40 border-b border-slate-800/60 text-xs">
        <p class="font-semibold text-slate-200 truncate">{{ auth()->user()->full_name }}</p>
        <span class="text-[11px] text-slate-400 uppercase">{{ auth()->user()->role->name }}</span>
    </div>

    <nav class="flex-1 px-3 py-4 space-y-1 overflow-y-auto">
        <a href="{{ route('dashboard') }}" class="flex items-center gap-3 px-3 py-2 text-xs rounded-lg {{ request()->routeIs('dashboard') ? 'bg-emerald-600 text-white font-semibold' : 'text-slate-300 hover:bg-slate-800' }}">
            <span>Dashboard Hasil</span>
        </a>

        @if(in_array(auth()->user()->role->name, ['admin', 'seleksi']))
        <a href="{{ route('seleksi.index') }}" class="flex items-center gap-3 px-3 py-2 text-xs rounded-lg {{ request()->routeIs('seleksi.index') ? 'bg-emerald-600 text-white font-semibold' : 'text-slate-300 hover:bg-slate-800' }}">
            <span>Tahap 1: Bilik Seleksi</span>
        </a>
        @endif

        <a href="{{ route('seleksi.rekap') }}" class="flex items-center gap-3 px-3 py-2 text-xs rounded-lg {{ request()->routeIs('seleksi.rekap') ? 'bg-emerald-600 text-white font-semibold' : 'text-slate-300 hover:bg-slate-800' }}">
            <span>Rekapitulasi Seleksi (Top 12)</span>
        </a>

        @if(in_array(auth()->user()->role->name, ['admin', 'guru']))
        <a href="{{ route('pleno.index') }}" class="flex items-center gap-3 px-3 py-2 text-xs rounded-lg {{ request()->routeIs('pleno.index') ? 'bg-emerald-600 text-white font-semibold' : 'text-slate-300 hover:bg-slate-800' }}">
            <span>Tahap 2: Musyawarah Pleno</span>
        </a>
        @endif

        @if(in_array(auth()->user()->role->name, ['admin', 'pemilihan']))
        <a href="{{ route('voting.bilik') }}" class="flex items-center gap-3 px-3 py-2 text-xs rounded-lg {{ request()->routeIs('voting.bilik') ? 'bg-emerald-600 text-white font-semibold' : 'text-slate-300 hover:bg-slate-800' }}">
            <span>Tahap 3: Bilik Suara E-Voting</span>
        </a>
        @endif

        @if(auth()->user()->role->name === 'admin')
        <div class="pt-3 pb-1 px-3 text-[10px] font-semibold text-slate-400 uppercase tracking-wider">Khusus Admin</div>
        <a href="{{ route('admin.absensi') }}" class="flex items-center gap-3 px-3 py-2 text-xs rounded-lg {{ request()->routeIs('admin.absensi') ? 'bg-emerald-600 text-white font-semibold' : 'text-slate-300 hover:bg-slate-800' }}">
            <span>Rekap Absensi Pemilih</span>
        </a>
        <a href="{{ route('admin.paslon') }}" class="flex items-center gap-3 px-3 py-2 text-xs rounded-lg {{ request()->routeIs('admin.paslon') ? 'bg-emerald-600 text-white font-semibold' : 'text-slate-300 hover:bg-slate-800' }}">
            <span>Penetapan 3 Paslon</span>
        </a>
        @endif
    </nav>

    <div class="p-3 border-t border-slate-800">
        <form action="{{ route('logout') }}" method="POST">
            @csrf
            <button type="submit" class="w-full py-2 px-3 text-xs text-rose-300 hover:bg-rose-950/40 rounded-lg text-left font-medium">
                Keluar Sesi
            </button>
        </form>
    </div>
</aside>
`,
  },
  {
    id: 'app-blade',
    name: 'app.blade.php (SweetAlert2)',
    path: 'resources/views/layouts/app.blade.php',
    category: 'Blade View',
    language: 'html',
    content: `<!DOCTYPE html>
<html lang="id" class="h-full bg-slate-50">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'E-Pilketos SMP Al Muttaqin') }}</title>

    <!-- Tailwind CSS (Vite / CDN) -->
    <script src="https://cdn.tailwindcss.com"></script>

    <!-- SweetAlert2 CDN (Versi Terbaru) -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <style>
        /* Penyesuaian tema SweetAlert2 agar selaras dengan Tailwind Emerald */
        .swal2-popup.pilketos-swal {
            border-radius: 1rem !important;
            font-family: inherit !important;
            box-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1) !important;
        }
        .swal2-confirm.pilketos-btn-emerald {
            background-color: #059669 !important;
            border-radius: 0.75rem !important;
            font-weight: 600 !important;
            padding: 0.625rem 1.25rem !important;
        }
        .swal2-cancel.pilketos-btn-cancel {
            background-color: #f1f5f9 !important;
            color: #334155 !important;
            border-radius: 0.75rem !important;
            font-weight: 600 !important;
            padding: 0.625rem 1.25rem !important;
        }
    </style>
</head>
<body class="h-full antialiased font-sans text-slate-800 bg-slate-50">
    <div class="flex h-screen overflow-hidden">
        <!-- Sidebar Navigation -->
        @include('layouts.sidebar')

        <!-- Main Content Area -->
        <main class="flex-1 overflow-y-auto p-6 md:p-8">
            @yield('content')
        </main>
    </div>

    <!-- ========================================================== -->
    <!-- GLOBAL SWEETALERT2 LISTENER UNTUK FLASH MESSAGES LARAVEL   -->
    <!-- ========================================================== -->
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                customClass: {
                    popup: 'pilketos-swal'
                }
            });

            @if(session('success'))
                Swal.fire({
                    icon: 'success',
                    title: 'Berhasil!',
                    text: "{{ session('success') }}",
                    iconColor: '#059669',
                    timer: 2500,
                    timerProgressBar: true,
                    confirmButtonText: 'Tutup',
                    customClass: {
                        popup: 'pilketos-swal',
                        confirmButton: 'pilketos-btn-emerald'
                    },
                    buttonsStyling: false
                });
            @endif

            @if(session('voting_success'))
                Swal.fire({
                    icon: 'success',
                    title: 'Suara Anda Berhasil Disimpan!',
                    html: '<div class="mt-2 text-center text-sm text-slate-600"><p>{{ session("voting_success") }}</p><p class="text-xs text-slate-400 mt-2 italic">Layar kembali ke menu absensi...</p></div>',
                    iconColor: '#059669',
                    timer: 3000,
                    timerProgressBar: true,
                    showConfirmButton: false,
                    allowOutsideClick: false,
                    customClass: {
                        popup: 'pilketos-swal'
                    }
                }).then(() => {
                    window.location.href = "{{ route('voting.bilik') }}";
                });
            @endif

            @if(session('error'))
                Swal.fire({
                    icon: 'error',
                    title: 'Terjadi Kesalahan',
                    text: "{{ session('error') }}",
                    iconColor: '#e11d48',
                    confirmButtonText: 'Tutup',
                    customClass: {
                        popup: 'pilketos-swal',
                        confirmButton: 'pilketos-btn-emerald'
                    },
                    buttonsStyling: false
                });
            @endif

            @if(session('warning'))
                Swal.fire({
                    icon: 'warning',
                    title: 'Perhatian',
                    text: "{{ session('warning') }}",
                    iconColor: '#d97706',
                    confirmButtonText: 'Mengerti',
                    customClass: {
                        popup: 'pilketos-swal',
                        confirmButton: 'pilketos-btn-emerald'
                    },
                    buttonsStyling: false
                });
            @endif

            @if($errors->any())
                Swal.fire({
                    icon: 'error',
                    title: 'Validasi Gagal',
                    html: '<ul class="text-left text-xs text-rose-700 list-disc pl-5 mt-2">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>',
                    iconColor: '#e11d48',
                    confirmButtonText: 'Perbaiki',
                    customClass: {
                        popup: 'pilketos-swal',
                        confirmButton: 'pilketos-btn-emerald'
                    },
                    buttonsStyling: false
                });
            @endif
        });

        /**
         * Global Helper JS untuk Konfirmasi Hapus Data dengan SweetAlert2
         * Digunakan pada tombol/form delete: onsubmit="return confirmDelete(event, this, 'Hapus siswa ini?')"
         */
        function confirmDelete(event, formElement, message = 'Data yang dihapus tidak dapat dipulihkan kembali.') {
            event.preventDefault();
            Swal.fire({
                title: 'Apakah Anda Yakin?',
                text: message,
                icon: 'warning',
                iconColor: '#d97706',
                showCancelButton: true,
                confirmButtonText: 'Ya, Hapus Data',
                cancelButtonText: 'Batal',
                reverseButtons: true,
                customClass: {
                    popup: 'pilketos-swal',
                    confirmButton: 'pilketos-btn-emerald',
                    cancelButton: 'pilketos-btn-cancel'
                },
                buttonsStyling: false
            }).then((result) => {
                if (result.isConfirmed) {
                    formElement.submit();
                }
            });
            return false;
        }
    </script>
    @stack('scripts')
</body>
</html>
`,
  },
];

